#fetching reviews from reviews table
import sqlite3
import os       #portable way to interact python pogram with os

DB_PATH = os.path.join(os.path.dirname(__file__),"store.db")


#it is fetching avg rating and reviews for the given product id.
def get_product_rating(product_id:int) -> dict:
    conn=sqlite3.connect(DB_PATH)
    c= conn.cursor()        #this creates cursor object for executing SQL commands
    c.execute(
        #? is placeholder so that we don't have to hardcode product id in where
        #In AI agent development, tool inputs generated by LLMs must be treated as untrusted user input. Parameterizing DB queries inside tools prevents indirect prompt injections or hallucinated payload strings from compromising the database layer."
        #comma at end of product_id suggest that this is tuple (and treat it as purely data rather then exutable code to prevent prompt injection), else it will be evaluated as integer and raises Typeerror on sqllite
        "SELECT AVG(rating), COUNT(*) FROM reviews WHERE product_id = ?", (product_id,),
    )
    row = c.fetchone()          #fetches first row as tuple
    conn.close()

    avg= round(row[0], 2) if row and row[0] is not None else 0.0    #rounds row[0] into 2 digits if condition fulfills
    count = row[1] if row else 0
    return  {"product_id": product_id, "average_rating": avg, "review_count":count}

def get_ratings_for_products(product_ids: list[int]) -> list [dict]:
    """return ratings for a list of product IDs"""
    if not product_ids:
        return[]            #early guard, doesn't open connection to DB if input is empty
    conn = sqlite3.connect(DB_PATH)
    c=conn.cursor()
    placeholders=",".join("?" * len(product_ids))   #creates list like ["?", "?", "?"] and joines it with "? , ? , ?"
    c.execute(
        f"""
        SELECT product_id, AVG(rating), COUNT(*)
        FROM reviews
        WHERE product_id IN ({placeholders})
        GROUP BY product_id
        """,
        product_ids
    )
    rows = c.fetchall()         #retrives all the rows as tuples
    conn.close()

    #transforming list into hashmap for O(1) complexity
    ratings_map= {r[0]: {"average_rating": round(r[1], 2), "review_count": r[2]} for r in rows}
    return [
        {
            "product_id":pid,
            "average_rating": ratings_map.get(pid, {}).get("average_rating",0.0),  #{} and 0.0 is the defult values incase the pid and average_rating variable are empty
            "review_count": ratings_map.get(pid, {}).get("review_count", 0),
        }
        for pid in product_ids
    ]

if __name__=="__main__":    #python automatically checks this and it will be true only if you execute this from terminal
    #single product
    result = get_product_rating(1)
    print("Single product rating")
    print(f"product {result['product_id']}: {result['average_rating']} stars {result['review_count']} reviews")

    #multiple products fetching 
    print("\n Batch rating:")
    results = get_ratings_for_products([1,3,5,7])
    for r in results: 
        print(f" Product {r['product_id']}:{r['average_rating']} stars ({r['review_count']} reviews)")